server:
  port: 12580
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/kitton_wang/config-test.git # 需要拉取配置的Git仓库地址
  rabbitmq:
    host: 192.168.164.134
    username: leyou
    password: 123321
    virtual-host: /
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/ # eureka地址
management:
  endpoints:
    web:
      exposure:
        include: "*"