server:
  port: 8080
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要写其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
spring:
  application:
    name: consumer-service
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients:
      - user-service
  ReadTimeout: 600 # 读取超时时间
  ConnectTimeout: 300 # 连接超时时间
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 1000
feign:
  hystrix:
    enabled: true # 开启feign中的hystrix效果
logging:
  level:
    com.wmq: debug